### ISSUE TITLE
Doc links permission denied

### ISSUE THREAD

**Issue by subsoap** [Jerakin/DefTree#1]
![2018-02-26 11_16_19-maze found _ read the docs](https://user-images.githubusercontent.com/409170/36690212-7c3f8a2e-1ae6-11e8-948a-467ea7ed7590.png)

**Comment by AGulev** [comment]
Magic, but a minute ago I tried the same link and wanted to open the same issue =)
first link "documentation" - works=)

**Comment by Jerakin** [comment]
Fixed. Broken links in the README.rst
