### ISSUE TITLE
game.project

### ISSUE THREAD

**Issue by AGulev** [Jerakin/DefTree#3]
is it possible to use deftree for reading game.project? I want to check is *.png file used somewhere but it can be used not only in atlases

**Comment by Jerakin** [comment]
The game.project file is the only one that DefTree can't read. This is because it is in a standard config format.
In python 3 you can use [configparser ](https://docs.python.org/3/library/configparser.html) for it instead.

**Comment by AGulev** [comment]
Cool! Thank you!
