### ISSUE TITLE
Errors after using delete_obsolete_resources.py

### ISSUE THREAD

**Issue by AGulev** [Jerakin/DefTree#4]
After using delete_obsolete_resources.py I can't open fixed gui in editor:
![2018-03-06_22-59-19](https://user-images.githubusercontent.com/2209596/37055157-05340678-2192-11e8-8ef8-8127a167a6c4.jpg)
I tryied to revert font removing, it didn't help. Looks like that the reason (quotes):
![2018-03-06_22-58-43](https://user-images.githubusercontent.com/2209596/37055139-fac8a266-2191-11e8-8722-601cefb68762.jpg)

**Comment by Jerakin** [comment]
Sorry about that! That is because a bug in DefTree 1.1.0
I made a new release (1.1.1) with a fix, so it should be resolved if you upgrade. `pip install deftree --upgrade`

**Comment by AGulev** [comment]
Works! Thank you!
